services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: index-scrapper
    working_dir: /app
    tty: true
    volumes:
      - ./data:/app/data
    environment:
      - LANG=C.UTF-8
      - DEBIAN_FRONTEND=noninteractive
      - TZ=America/Costa_Rica
      - HTTP_USER=example_user
      - HTTP_PASSWORD=example_password
      - DB_TYPE=ExampleDB
      - DB_URL=https://example.supabase.co
      - DB_USER=example_db_user
      - DB_PASSWORD=example_db_password
      - RCLONE_REMOTE=example_remote
      - RCLONE_OPTIONS=example_options
      - RCLONE_CONFIG=/example/path/to/rclone/config
    command: ["--url", "https://example.url/path", "--site_type", "achrou/goindex", "--simultaneous", "3", "--limit", "10", "--stats-one-line", "--use-auth", "--group-name", "ExampleGroup", "--base-folder", "/app/data", "--delete-after"]
